### ISSUE TITLE
Actor sheet does not work...

### ISSUE THREAD

**Issue by WildBillLives** [McArthur-Alford/woinfoundry#2]
I installed the system manually into my foundry data/worlds folder, but the actor sheet does not function properly:

1) The sheet is missing the Attributes section, 
2) Values will not be retained when you enter them on any other section of the sheet, 
3) Equipment or other items cannot be dragged/dropped into the sheet (nothing happens when you try to do so).

Thanks.

**Comment by mira-alford** [comment]
Hello. There is now a version of WOIN that runs on foundry 0.8.8, which should have fixed all your issues.
